#### Exercise: 
- Use following CrossEntropy loss for emotional classification using Transformer architecture. 
- Optimize learning-rate value to get over 60 % accuracy 

![loss](../../img/dl_tutorial-Trang-3.png)

In [15]:
import torch 
from torch import nn 
import math

# Setting for model architecture  
d_model = 100
embedding_size = d_model
batch_size = 3
num_of_labels = 8


# fake input data, #NOTE `fake_gold_label` should be integer or long values, can not be float values
fake_sent_vector = torch.rand(batch_size, embedding_size) 
fake_gold_label = torch.randint(low=0, high=num_of_labels, size=(batch_size, )) 

# MODEL INSTALL  
# NOTE: output layer transform to the important values for each label 
output_layer = torch.nn.Linear(embedding_size, num_of_labels)

# install loss function.
loss_function = nn.CrossEntropyLoss() 

# MODEL COMPUTING 
# using softmax to compute probabilities
softmax_layer = torch.nn.Softmax(dim=1)  # Set `dim=1` because this dimentions present probabilities across all class of 1 sample 
label_feature_values = output_layer(fake_sent_vector)
class_probabilities = softmax_layer(label_feature_values)



# forward 
loss = loss_function(class_probabilities, fake_gold_label)

# output shape 
print('probabilities for 3 sentences, 8 labels = \n', class_probabilities)
print('fake gold label 3 sentences \n', fake_gold_label)
print('loss = ', loss)


#NOTE - from probabilities, we pick the position of the largest value as a model label prediction 
predictions = torch.argmax(class_probabilities, dim=1)
print('label predictions \n', predictions)



probabilities for 3 sentences, 8 labels = 
 tensor([[0.0817, 0.1935, 0.0937, 0.2273, 0.1017, 0.1177, 0.0944, 0.0901],
        [0.0832, 0.1460, 0.1091, 0.1764, 0.1365, 0.1345, 0.1145, 0.0999],
        [0.0865, 0.1725, 0.1162, 0.1885, 0.1494, 0.1131, 0.1046, 0.0692]],
       grad_fn=<SoftmaxBackward0>)
fake gold label 3 sentences 
 tensor([3, 2, 3])
loss =  tensor(2.0303, grad_fn=<NllLossBackward0>)
label predictions 
 tensor([3, 3, 3])
