**Exercise**

Given bellow magic numbers, design a Neural Network (Feed Forward Network) to find next 10 numbers of this magic number array. And show why and how it work??

**tips**: *the next number maybe is generated by the previous numbers (similar to Fibonacci array) following a magic **rule**. You need to design a network and construct the data to learn that rule*

In [1]:
magic_numbers = magic_numbers = [0.027344444444444435, 0.015032777777777777, 0.02032391666666666, -0.013204084722222224, 0.0005077097916666583, -0.01200313854513889, 0.0013690679133680486, -0.01222794455608507, 0.002963575844158414, -0.01217918427038674, 0.005073481154240772, -0.011378390818949846, 0.006788408660818075, -0.011081862591338129, 0.008273188158746777, -0.011153535102891252, 0.009575561464089293, -0.011512203210823286, 0.010729044382965352, -0.01208852003359754, 0.011816479599100106, -0.012834693225877658, 0.01289028913340389, -0.01371803975617296, 0.01398657288966323, -0.014717929286432662, 0.015131143025676544, -0.01582451941014425, 0.016342754740021448, -0.017034527599041706, 0.017635731458175787, -0.018348984892655514, 0.019021828159005313, -0.019771855103278495, 0.02051151782901413, -0.02130912986206256, 0.022114768022487824, -0.02296828909105081, 0.023841537326162104, -0.02475799746665584, 0.025702099536502154, -0.026687948416656275, 0.027707260209689968, -0.028768797126266423, 0.029868510858425002, -0.03101214913537993, 0.03219814835102315, -0.033430584151233234, 0.034709376091536445, -0.036037702816867315, 0.03741639695320151, -0.03884818942765905, 0.04033450406996608, -0.04187788668711131, 0.043480173270439106, -0.045143880430979076, 0.046871159576741775, -0.04866459334706626, 0.050526599416108, -0.05245988737961829, 0.054467119760474365, -0.056551174911190896, 0.05871495517821266, -0.06096153906976705, 0.06329407367049159, -0.06571586367909749, 0.06823031212416737, -0.07084097349309473, 0.07355152221545157, -0.07636578545250924, 0.07928772762772039, -0.08232147178692491, 0.08547129349352899, -0.08874163586492663, 0.09213710903003615, -0.09566250177466229, 0.09932278440585271, -0.10312311869875553, 0.10706886295439767, -0.11116558123343942, 0.11541904993358808, -0.1198352668931399, 0.12442045912399101, -0.12918109213950021, 0.1341238786576102, -0.13925578837881505, 0.1445840575776386, -0.15011619948476995, 0.15586001474627978, -0.1618236025249825, 0.1680153718437211, -0.17444405350084835, 0.18111871233720556, -0.1880487600513746, 0.195243968445642, -0.20271448322384938, 0.21047083828312935, -0.21852397057821313, 0.2268852355350357, -0.23556642306879952, 0.2445797742038232, -0.25393799833769887, 0.2636542911596765, -0.2737423532594428, 0.2842164094442954, -0.295091228798177, 0.30638214550614934, -0.31810508047722547, 0.33027656379336384, -0.3429137580183086, 0.3560344823976093, -0.36965723798510236, 0.3838012337304084, -0.3984864135648923, 0.4137334845237796, -0.42956394594445935, 0.44600011978186144, -0.4630651820838686, 0.4807831956709846, -0.49917914406646036, 0.5182789667246296, -0.5381095956071981, 0.5586989931590085, -0.5800761917368691, 0.6022713345470133, -0.6253157181489366, 0.6492418365855286, -0.6740834272017365, 0.6998755182163611, -0.7266544781140676, 0.7544580669272569, -0.7833254894801063, 0.8132974506698595, -0.8444162128633129, 0.8767256554894365, -0.9102713369121491, 0.9451005586705055, -0.9812624321768644, 1.018807947967098, -1.0577900476004807, 1.098263698310648, -1.1402859705128823, 1.1839161182770193, -1.2292156628794462, 1.276248479552004, -1.3250808875501168, 1.3757817436671504, -1.4284225393268577, 1.4830775013908242, -1.5398236968230494, 1.598741141359258, -1.6599129123341614, 1.723425265825772, -1.7893677582819452, 1.857833372800651, -1.9289186502420455, 2.0027238253572026, -2.0793529681254777, 2.1589141304997774, -2.241519498766671, 2.32728555173617, -2.4163332249842404, 2.508788081379639, -2.604780488135522, 2.704445800635489, -2.8079245532932573, 2.9153626577151073, -3.026911608444498, 3.1427286965789905, -3.262977231560668, 3.3878267714528185, -3.5174533620275517, 3.6520397850015147, -3.7917758157697046, 3.936858491000816, -4.087492386471446, 4.243889905530916, -4.40627157860347, 4.574866374150168, -4.749912021528935, 4.931655346208046, -5.1203526178056915, 5.316269911446397, -5.519683482943829, 5.730880158339026, -5.950157738343302, 6.177825418256154, -6.41420422395024, 6.659627464538238, -6.914441202359829, 7.179004740951563, -7.45369113168763, 7.738887699805974, -8.034996590561446, 8.342435336276132, -8.66163744508641, 8.99305301221693]
print('total numbers = ', len(magic_numbers))


total numbers =  197


In [2]:
import torch
# =====================
# generate data
def gen_fake_data(): 

    x_train = [magic_numbers[i-10:i] for i in range(10, len(magic_numbers))]
    y_train = [[magic_numbers[i]] for i in range(10, len(magic_numbers))]
    return x_train, y_train 
     
# gen training data sample 
x_train, y_train  = gen_fake_data( )
print(x_train[:3])
print(y_train[:3])
# =====================

[[0.027344444444444435, 0.015032777777777777, 0.02032391666666666, -0.013204084722222224, 0.0005077097916666583, -0.01200313854513889, 0.0013690679133680486, -0.01222794455608507, 0.002963575844158414, -0.01217918427038674], [0.015032777777777777, 0.02032391666666666, -0.013204084722222224, 0.0005077097916666583, -0.01200313854513889, 0.0013690679133680486, -0.01222794455608507, 0.002963575844158414, -0.01217918427038674, 0.005073481154240772], [0.02032391666666666, -0.013204084722222224, 0.0005077097916666583, -0.01200313854513889, 0.0013690679133680486, -0.01222794455608507, 0.002963575844158414, -0.01217918427038674, 0.005073481154240772, -0.011378390818949846]]
[[0.005073481154240772], [-0.011378390818949846], [0.006788408660818075]]


In [3]:
from torch.utils.data import DataLoader

# dataloader
# dataset_example should support operator index_selection for create the data_loader object
train_loader = DataLoader([(torch.Tensor(x_train[i]), torch.Tensor(y_train[i])) for i in range(len(x_train))], batch_size=60, collate_fn=None, shuffle=True)

In [11]:
# train a model to find hidden "weights and bias" from training data.
# TODO, practice with learning rate equal to 0.005, 0.02 0.01 to see the result how the model work 

# ============= ############## ===============
# USE LIBRARY
model = torch.nn.Linear(10,1)
model.cuda()

# loss also is supported by a library 
loss_computation = torch.nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr = 1e-3)
# ============= ############## ===============

MAX_EPOCHS=5000
for epoch in range(MAX_EPOCHS):
    avg_loss = 0.0
    for batch in train_loader:

        x, y_gold = batch
  
        x = x.cuda()
        y_gold = y_gold.cuda()
        
        # Forward pass: Compute predicted y by passing x to the model
        y_pred = model(x)


        # ============= ############## ===============
        # Compute and loss = average ((out_put - pred) ^ 2)
        loss = loss_computation(y_pred, y_gold)
        # ============= ############## ===============

        # perform a backward pass (backpropagation) => to compute the gradient values in Tensor weights
        loss.backward()
        avg_loss += loss.item()

        # ============= ############## ===============
        # USE LIBRARY: 'model.parameters()' in stead of 'model.get_parameter()' is implemented by library, also return list of parameters: "weight" and "bias" 
        # Optimizer step(), this update gradient values to weights.
        optimizer.step() # instead of `param.add_(-lr * param.grad)` => update weight values
        optimizer.zero_grad() # instead of `param.grad.fill_(0)` => remove all the old gradient values in all Tensor weight
        # ============= ############## ===============

    avg_loss = avg_loss / len(train_loader)
    if avg_loss < 0.0000001:
        break
    print('epoch/batch: ', epoch, 'avg loss: ', avg_loss)

print(model.weight,  model.bias) 

epoch/batch:  0 avg loss:  0.14361311681568623
epoch/batch:  1 avg loss:  0.07923163007944822
epoch/batch:  2 avg loss:  0.057618374936282635
epoch/batch:  3 avg loss:  0.045393263921141624
epoch/batch:  4 avg loss:  0.03798386920243502
epoch/batch:  5 avg loss:  0.028067756909877062
epoch/batch:  6 avg loss:  0.02554726554080844
epoch/batch:  7 avg loss:  0.024827954825013876
epoch/batch:  8 avg loss:  0.02392716985195875
epoch/batch:  9 avg loss:  0.02329772152006626
epoch/batch:  10 avg loss:  0.022951824590563774
epoch/batch:  11 avg loss:  0.02211264194920659
epoch/batch:  12 avg loss:  0.02174754487350583
epoch/batch:  13 avg loss:  0.02155477413907647
epoch/batch:  14 avg loss:  0.021120411343872547
epoch/batch:  15 avg loss:  0.020742798689752817
epoch/batch:  16 avg loss:  0.020432050805538893
epoch/batch:  17 avg loss:  0.02008042111992836
epoch/batch:  18 avg loss:  0.0198304308578372
epoch/batch:  19 avg loss:  0.019516787957400084
epoch/batch:  20 avg loss:  0.019135831855

In [10]:
gold = [ -9.337149354643437, 9.69441167003935, -10.065343720935275, 10.450468545056113, -10.850329192837462, 11.26548949316116, -11.696534848389796, 12.144073059821169, -12.608735184726696, 13.091176426182173]
new_nums = magic_numbers[-10:]
for i in range(10):
    new_nums = new_nums[-10:]
    new_pred = model(torch.Tensor(new_nums).cuda())
    print(new_pred, gold[i])

    new_nums.append(new_pred)

tensor([-9.3097], device='cuda:0', grad_fn=<AddBackward0>) -9.337149354643437
tensor([9.6646], device='cuda:0', grad_fn=<AddBackward0>) 9.69441167003935
tensor([-10.0261], device='cuda:0', grad_fn=<AddBackward0>) -10.065343720935275
tensor([10.3977], device='cuda:0', grad_fn=<AddBackward0>) 10.450468545056113
tensor([-10.7971], device='cuda:0', grad_fn=<AddBackward0>) -10.850329192837462
tensor([11.2067], device='cuda:0', grad_fn=<AddBackward0>) 11.26548949316116
tensor([-11.6232], device='cuda:0', grad_fn=<AddBackward0>) -11.696534848389796
tensor([12.0639], device='cuda:0', grad_fn=<AddBackward0>) 12.144073059821169
tensor([-12.5237], device='cuda:0', grad_fn=<AddBackward0>) -12.608735184726696
tensor([12.9860], device='cuda:0', grad_fn=<AddBackward0>) 13.091176426182173
